name: seals
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy<1.24
  - scipy
  - matplotlib
  - xarray
  - netcdf4
  - pandas
  - scikit-learn
  - pyyaml
  - pytest
  - pip
  - jupyter
  - jupyterlab
  - tqdm
  - numba
<<<<<<< HEAD
=======
  - cython
  - metpy
  - dask
>>>>>>> 0a2289ea74d47396011d37f7bda551721409d7e9
  - pip:
    - tensorflow
    - keras_core
    - bridgescaler
    - pytest
    - .
