name: sealstf
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - matplotlib
  - xarray
  - netcdf4
  - pandas
  - scikit-learn
  - pyyaml
  - pytest
  - pip
  - jupyter
  - jupyterlab
  - tqdm
  - numba
  - cython
  - metpy=1.6.1
  - dask
  - pip:
    - bridgescaler
    - hagelslag
    - .
