name: seals
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - matplotlib
  - xarray
  - netcdf4
  - pandas
  - scikit-learn
  - pyyaml
  - pytest
  - pip
  - jupyter
  - jupyterlab
  - tqdm
  - sphinx
  - numba
  - cython
  - metpy
  - pip:
    - bridgescaler
    - pytest
    - dask
    - .
