#data_path: "/glade/u/home/bryant/work/SEALS_training_data/data_gen_20240422/"
data_path: "/glade/derecho/scratch/bryant/work/SEALS_training_data/data_gen_20240426/"
out_path: "/glade/u/home/bryant/work/SEALS_output/train/"
random_seed: 812
save_model: True
save_output: True
validation_ratio: 0.2
sensor_type_mask: -999
sensor_exist_mask: -1
scaler_type: "quantile"
#models: ['transformer_leak_rate']
models: ['backtracker']
transformer_leak_loc:
  kwargs:
    encoder_layers: 2
    decoder_layers: 2
    hidden_size: 128
    n_heads: 8
    num_quantized_embeddings: 500
    hidden_activation: "relu"
    output_activation: "sigmoid"
    dropout_rate: 0.2
    use_quantizer: 0
    quantized_beta: 0.25
    n_outputs: 1
    min_filters: 4
    kernel_size: 3
    filter_growth_rate: 2
    n_conv_layers: 3
    pooling: "average"
    pool_size: 2
    padding: "valid"
  fit:
    epochs: 70
    verbose: 1
    batch_size: 1024
  compile:
    loss: "binary_crossentropy"
    optimizer: "adam"
    metrics: ["binary_accuracy"]
transformer_leak_rate:
  kwargs:
    encoder_layers: 2
    hidden_size: 128
    n_heads: 2
    num_quantized_embeddings: 500
    hidden_activation: "relu"
    output_activation: "linear"
    dropout_rate: 0.4
    use_quantizer: True
    quantized_beta: 0.25
    n_outputs: 1
    min_filters: 4
    kernel_size: 3
    filter_growth_rate: 2
    n_conv_layers: 3
    pooling: "max"
    pool_size: 10
    padding: "valid"
  fit:
    epochs: 20
    verbose: 1
    batch_size: 512
  compile:
    loss: "mse"
    optimizer: "adam"
    metrics: [ "mse" ]
backtracker:
  kwargs:
    hidden_layers: 3
    hidden_neurons: 64
    activation: 'relu'
    optimizer: 'SGD'
    lr: 0.001
    l2_weight: 0.00001
    batch_size: 1
    use_dropout: False
    dropout_alpha: 0.0
    epochs: 20
    verbose: 1
  fit:
    kwargs: None
  compile:
    loss: 'mse'
gaussian_process:
  kwargs:
    num_met_sensors: 1
    normalize_y: True
    n_restarts_optimizer: 4
    length_scale_bounds: "fixed"
  fit:
    epochs: None
predict_batch_size: 1


