data_path: "/glade/derecho/scratch/username/SEALS_training_data/data_gen_20240717/"
out_path: "/glade/derecho/scratch/username/SEALS_output/"
random_seed: 812
save_model: True
save_output: True
validation_ratio: 0.2
sensor_type_mask: -999
sensor_exist_mask: -1
scaler_type: "quantile"
#scaler_path: "/glade/derecho/scratch/dgagne/SEALS_output/scalers_2024-07-18_2207/"
scaler_options:
  compression: 500
  distribution: "uniform"
predict_batch_size: 10000
models: ['loc_rate_block_transformer']
loc_rate_block_transformer:
  kwargs:
    encoder_layers: 4
    decoder_layers: 3
    hidden_size: 256
    n_heads: 12
    hidden_activation: "relu"
    output_activation: "softmax"
    dropout_rate: 0.2
    n_outputs: 1
    block_size: 10
    n_coords: 3
    data_start_index: 4
  fit:
    epochs: 100
    verbose: 1
    batch_size: 512
  compile:
    loss: ["categorical_crossentropy", "mean_absolute_error"]
    loss_weights: [1.0, 1.0]
  optimizer:
    learning_rate: 0.0001
    optimizer_type: "adam"
    adam_beta_1: 0.9
    adam_beta_2: 0.999
    epsilon: 0.0000001
    sgd_momentum: 0
block_transformer_leak_loc:
  kwargs:
    encoder_layers: 4
    decoder_layers: 3
    hidden_size: 256
    n_heads: 12
    hidden_activation: "relu"
    output_activation: "softmax"
    dropout_rate: 0.1
    n_outputs: 1
    block_size: 10
    n_coords: 3
    data_start_index: 4
  fit:
    epochs: 30
    verbose: 2
    batch_size: 256
  compile:
    loss: "categorical_crossentropy"
    metrics: ["categorical_accuracy"]
  optimizer:
    learning_rate: 0.0001
    optimizer_type: "adam"
    adam_beta_1: 0.9
    adam_beta_2: 0.999
    epsilon: 0.0000001
    sgd_momentum: 0
transformer_leak_loc:
  kwargs:
    encoder_layers: 4
    decoder_layers: 2
    hidden_size: 128
    n_heads: 8
    num_quantized_embeddings: 500
    hidden_activation: "relu"
    output_activation: "sigmoid"
    dropout_rate: 0.2
    use_quantizer: 0
    quantized_beta: 0.25
    n_outputs: 1
    min_filters: 4
    kernel_size: 3
    filter_growth_rate: 2
    n_conv_layers: 3
    pooling: "average"
    pool_size: 2
    padding: "valid"
  fit:
    epochs: 70
    verbose: 1
    batch_size: 1024
  compile:
    loss: "binary_crossentropy"
    metrics: ["binary_accuracy"]
  optimizer:
    learning_rate: 0.001
    optimizer_type: "adam"
    adam_beta_1: 0.9
    adam_beta_2: 0.999
    epsilon: 0.0000001
    sgd_momentum: 0
transformer_leak_rate:
  kwargs:
    encoder_layers: 2
    hidden_size: 128
    n_heads: 2
    num_quantized_embeddings: 500
    hidden_activation: "relu"
    output_activation: "linear"
    dropout_rate: 0.4
    use_quantizer: True
    quantized_beta: 0.25
    n_outputs: 1
    min_filters: 4
    kernel_size: 3
    filter_growth_rate: 2
    n_conv_layers: 3
    pooling: "max"
    pool_size: 10
    padding: "valid"
  fit:
    epochs: 20
    verbose: 1
    batch_size: 512
  compile:
    loss: "mse"
    metrics: [ "mse" ]
  optimizer:
    learning_rate: 0.001
    optimizer_type: "adam"
    adam_beta_1: 0.9
    adam_beta_2: 0.999
    epsilon: 0.0000001
    sgd_momentum: 0
backtracker:
  kwargs:
    hidden_layers: 1
    hidden_neurons: 128
    activation: 'relu'
    n_output_tasks: 4
    optimizer: 'adam'
    lr: 0.001
    l2_weight: 0.00001
    batch_size: 128
    use_dropout: False
    dropout_alpha: 0.2
    epochs: 20
    verbose: 1
  preprocess:
    n_sensors: 3
    x_width: 40
    y_width: 40 
    factor_x: 0.4 
    factor_y: 0.4
  fit:
    kwargs: None
  compile:
    loss: "mse"
  optimizer:
    learning_rate: 0.001
    optimizer_type: "adam"
    adam_beta_1: 0.9
    adam_beta_2: 0.999
    epsilon: 0.0000001
    sgd_momentum: 0
gaussian_process:
  kwargs:
    num_met_sensors: 1
    normalize_y: True
    n_restarts_optimizer: 4
    length_scale_bounds: "fixed"
  fit:
    epochs: None


